package test.websvc.client.sf.bsp_oisp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-10-13T17:19:34.787+08:00
 * Generated source version: 3.0.5
 * 
 */
@WebServiceClient(name = "CommonExpressServiceService", 
                  wsdlLocation = "http://bsp-oisp.sf-express.com/bsp-oisp/ws/sfexpressService?wsdl",
                  targetNamespace = "http://service.expressservice.integration.sf.com/") 
public class CommonExpressServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.expressservice.integration.sf.com/", "CommonExpressServiceService");
    public final static QName CommonExpressServicePort = new QName("http://service.expressservice.integration.sf.com/", "CommonExpressServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://bsp-oisp.sf-express.com/bsp-oisp/ws/sfexpressService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CommonExpressServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://bsp-oisp.sf-express.com/bsp-oisp/ws/sfexpressService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CommonExpressServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CommonExpressServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommonExpressServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IExpressService
     */
    @WebEndpoint(name = "CommonExpressServicePort")
    public IExpressService getCommonExpressServicePort() {
        return super.getPort(CommonExpressServicePort, IExpressService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IExpressService
     */
    @WebEndpoint(name = "CommonExpressServicePort")
    public IExpressService getCommonExpressServicePort(WebServiceFeature... features) {
        return super.getPort(CommonExpressServicePort, IExpressService.class, features);
    }

}
