package test.websvc.client.sf.bsp_oisp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-10-13T17:19:34.753+08:00
 * Generated source version: 3.0.5
 * 
 */
@WebService(targetNamespace = "http://service.expressservice.integration.sf.com/", name = "IExpressService")
@XmlSeeAlso({ObjectFactory.class})
public interface IExpressService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sfexpressService", targetNamespace = "http://service.expressservice.integration.sf.com/", className = "cn.com.dgpost.websvc.client.sf.bsp_oisp.SfexpressService")
    @WebMethod
    @ResponseWrapper(localName = "sfexpressServiceResponse", targetNamespace = "http://service.expressservice.integration.sf.com/", className = "cn.com.dgpost.websvc.client.sf.bsp_oisp.SfexpressServiceResponse")
    public java.lang.String sfexpressService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
