package test.websvc.client.sf.cbta;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-10-13T17:20:20.325+08:00
 * Generated source version: 3.0.5
 * 
 */
@WebService(targetNamespace = "http://appservice.sfexpress.business.ieca.sf.com/", name = "SfexpressService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SfexpressService {

    @WebResult(name = "return", targetNamespace = "http://appservice.sfexpress.business.ieca.sf.com/", partName = "return")
    @WebMethod
    public java.lang.String sfexpressService(
        @WebParam(partName = "xml", name = "xml")
        java.lang.String xml,
        @WebParam(partName = "verifyCode", name = "verifyCode")
        java.lang.String verifyCode
    );
}
